### ISSUE TITLE
How can I run the code in Python?

### ISSUE THREAD

**Issue by aithlab** [INET-Complexity/housing-model#98]
Thanks for sharing the interesting project.

I've tried to run the code in Python, but the codes for Python which are in src/main/resources could not run.
I think that most of them require "was_wave_3_hhold_eul_final.dta" file. 
Where can I download the data? or Could you share the dataset?

Regards,

**Comment by adrian-carro** [comment]
Hi @aithlab,
Thanks for the interest. In general, unfortunately we cannot share the datasets used, as we are not the owners. Regarding the specific dataset you are asking about, the Wealth and Assets Survey, you can find more information on how to access it via the main UK data service, https://ukdataservice.ac.uk/.
In any case, note that the main point of this repository is to provide the code for the model itself, which is written in java. The python code is used to work with data, estimate and calibrate model parameters and potentially plot model results. As such, most of it is not supposed to run directly, as different users might not have access to the datasets and even if they do, their addresses are bound to be different. The main idea behind sharing that code is to allow researchers and users to see how we worked with data, thus potentially providing them with ideas on how to do their own data work and calibrations. For more information on how we estimated and calibrated the different model parameters, as well as the data sources used, please check the online appendix of our paper at https://www.bde.es/f/webbde/SES/Secciones/Publicaciones/PublicacionesSeriadas/DocumentosTrabajo/22/Files/dt2217e.pdf (also to appear soon published at the Industrial and Corporate Change journal).
Hope this helps.
Best regards,
Adrian Carro.

**Comment by aithlab** [comment]
Thanks for the reply!
